language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - pip install coveralls coverage nose
script:
    nosetests --with-coverage -vv --cover-package=nframe_client,nframe_server
after_success:
    coveralls debug