language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    nosetests --with-coverage -vv --cover-package=nframe_client,nframe_server
after_success:
    coveralls